@baseUrl = https://8080-matheusmora-aprendendoa-ycuhwb2apuc.ws-us115.gitpod.io

###
GET {{baseUrl}}/tarefa

###
POST {{baseUrl}}/tarefa
Content-Type: application/json

{
    "descricao": "Kashimba",
    "concluido": "TRUE"
}

###

GET {{baseUrl}}/tarefa/2

###

PUT {{baseUrl}}/tarefa/1
Content-Type: application/json

{
    "descricao": "Jerso",
    "concluido": "sim"
}


###

DELETE {{baseUrl}}/tarefa/13