@baseUrl = https://8080-matheusmora-atividadeap-hcyyn3fmqjj.ws-us115.gitpod.io

###
GET {{baseUrl}}/tarefa

###
POST {{baseUrl}}/tarefa
Content-Type: application/json

{
    "descricao": "Kashimba",
    "concluido": "FALSE"
}

###

GET {{baseUrl}}/tarefa/2

###

PUT {{baseUrl}}/tarefa/2
Content-Type: application/json

{
    "descricao": "Jerso",
    "concluido": "TRUE"
}


###

DELETE {{baseUrl}}/tarefa/13