@baseUrl = https://8080-matheusmora-atividadeap-hcyyn3fmqjj.ws-us116.gitpod.io

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6InVzZXIiLCJleHAiOjE3MjU0MDMwNDh9.zA4daFcGGaYNbQHdLJTEyaOeXf3hOFl1GRVkrEQjp_8
###
GET {{baseUrl}}/tarefa
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/tarefa
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Kashimba",
    "concluido": "FALSE"
}

###

GET {{baseUrl}}/tarefa/2

###

PUT {{baseUrl}}/tarefa/2
Content-Type: application/json

{
    "descricao": "Jerso",
    "concluido": "TRUE"
}


###

DELETE {{baseUrl}}/tarefa/13